CREATE TABLE racas (
    id              VARCHAR(64)   PRIMARY KEY,
    nome            VARCHAR(120)  NOT NULL,
    categoria       VARCHAR(60),
    tamanho         VARCHAR(60),
    deslocamento    VARCHAR(60),
    imagem_url      VARCHAR(255),
    descricao       TEXT
);

CREATE TABLE raca_tracos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raca_id     VARCHAR(64) NOT NULL REFERENCES racas(id) ON DELETE CASCADE,
    texto       TEXT NOT NULL,
    ordem       INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE raca_habilidades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raca_id     VARCHAR(64) NOT NULL REFERENCES racas(id) ON DELETE CASCADE,
    nome        VARCHAR(120) NOT NULL,
    descricao   TEXT NOT NULL,
    ordem       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_raca_tracos_raca_id ON raca_tracos(raca_id);
CREATE INDEX idx_raca_habilidades_raca_id ON raca_habilidades(raca_id);
