-- ===== Raça (tabela principal) =====
CREATE TABLE racas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(64)   NOT NULL UNIQUE,   -- pra URL, pode mudar junto com o nome
    nome              VARCHAR(120)  NOT NULL,
    categoria         VARCHAR(20)   NOT NULL
                          CHECK (categoria IN ('global', 'tribal', 'mistica', 'sobrenatural')),

    deslocamento      DOUBLE PRECISION NOT NULL,          -- base de caminhada, em metros (várias raças convertidas de pés dão valores como 4.5/7.5/10.5)

    tamanho           VARCHAR(20)   NOT NULL                  -- mecânico (regras), não numérico
                          CHECK (tamanho IN ('miudo', 'pequeno', 'medio', 'grande', 'enorme')),

    quote             VARCHAR(200),                           -- frase de efeito, exibida no topo da ficha

    idiomas           VARCHAR(5000),

    -- texto livre
    anatomia          VARCHAR(5000),
    aparencia         VARCHAR(5000),
    nomes_raciais     VARCHAR(5000),
    tracos_culturais  VARCHAR(5000),

    criado_em         TIMESTAMP     NOT NULL DEFAULT now(),
    atualizado_em     TIMESTAMP     NOT NULL DEFAULT now()
);

-- ===== Atributos (fixo ou à escolha) =====
CREATE TABLE raca_atributos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raca_id               BIGINT NOT NULL REFERENCES racas(id) ON DELETE CASCADE,
    atributo              VARCHAR(20)
                              CHECK (atributo IN ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor                 INT NOT NULL,
    quantidade_escolhas   INT,
    ordem                 INTEGER NOT NULL DEFAULT 0,
    CHECK (
        (atributo IS NOT NULL AND quantidade_escolhas IS NULL)
        OR
        (atributo IS NULL AND quantidade_escolhas IS NOT NULL)
    )
);

CREATE INDEX idx_raca_atributos_raca_id ON raca_atributos(raca_id);

-- ===== Altura — referência numérica (3 pontos) =====
CREATE TABLE raca_altura (
    raca_id       BIGINT PRIMARY KEY REFERENCES racas(id) ON DELETE CASCADE,
    valor_menor   DOUBLE PRECISION NOT NULL,   -- metros, ex: 1.40
    valor_medio   DOUBLE PRECISION NOT NULL,   -- ex: 1.80
    valor_maior   DOUBLE PRECISION NOT NULL    -- ex: 2.10
);

-- ===== Peso — referência numérica (3 pontos) =====
CREATE TABLE raca_peso (
    raca_id       BIGINT PRIMARY KEY REFERENCES racas(id) ON DELETE CASCADE,
    valor_menor   DOUBLE PRECISION NOT NULL,   -- kg
    valor_medio   DOUBLE PRECISION NOT NULL,
    valor_maior   DOUBLE PRECISION NOT NULL
);

-- ===== Idade — 2 marcos (maturidade + expectativa de vida) =====
CREATE TABLE raca_idade (
    raca_id             BIGINT PRIMARY KEY REFERENCES racas(id) ON DELETE CASCADE,
    idade_adulta        INT NOT NULL,   -- ex: 70 (elfo atinge maturidade aos 70)
    expectativa_vida    INT NOT NULL    -- ex: 500 (vive até 500 anos)
);

-- ===== Habilidades especiais =====
CREATE TABLE raca_habilidade_especial (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raca_id     BIGINT NOT NULL REFERENCES racas(id) ON DELETE CASCADE,
    nome        VARCHAR(120) NOT NULL,
    descricao   VARCHAR(5000) NOT NULL,
    tipo        VARCHAR(20) NOT NULL
                    CHECK (tipo IN ('passiva', 'uso_unico', 'multiplos_usos')),
    ordem       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_raca_habilidade_especial_raca_id ON raca_habilidade_especial(raca_id);

-- ===== Imagem (binário, própria do site) =====
CREATE TABLE raca_imagem (
    raca_id         BIGINT PRIMARY KEY REFERENCES racas(id) ON DELETE CASCADE,
    conteudo        BYTEA NOT NULL,
    content_type    VARCHAR(50) NOT NULL,
    tamanho_bytes   INTEGER NOT NULL,
    atualizado_em   TIMESTAMP NOT NULL DEFAULT now()
);
