CREATE TABLE talentos (
    id          VARCHAR(64)  PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    categoria   VARCHAR(60),
    icone       VARCHAR(20),
    prereq      VARCHAR(255),
    descricao   TEXT
);

CREATE TABLE talento_beneficios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talento_id  VARCHAR(64) NOT NULL REFERENCES talentos(id) ON DELETE CASCADE,
    texto       TEXT NOT NULL,
    ordem       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_talento_beneficios_talento_id ON talento_beneficios(talento_id);
