CREATE TABLE talentos (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                                VARCHAR(64)   NOT NULL UNIQUE,
    nome                                VARCHAR(120)  NOT NULL,

    -- Símbolo exibido no compêndio (emoji), ex: '⚔️'.
    icone                               VARCHAR(20),

    historia                            TEXT,
    descricao                           TEXT,

    -- Pré-requisito — talentos normais só têm o de atributo (o de raça é
    -- exclusivo dos talentos raciais, tabela à parte logo abaixo).
    atributo_requerido                  VARCHAR(20)
                                             CHECK (atributo_requerido IN
                                                 ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor_minimo_atributo_requerido     INT,

    CHECK (
        (atributo_requerido IS NULL) = (valor_minimo_atributo_requerido IS NULL)
    )
);

-- ===== Atributos recebidos ao pegar o talento (fixo ou à escolha) =====
-- Mesma estrutura de raca_atributos: dá pra ter mais de um bônus, cada um fixo
-- num atributo ou "à escolha" entre N. Fica separada em vez de colunas soltas
-- em talentos pra poder ser renderizada como cards destacados (igual raça),
-- e não só como texto solto na descrição.
CREATE TABLE talento_atributos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talento_id            BIGINT NOT NULL REFERENCES talentos(id) ON DELETE CASCADE,
    atributo              VARCHAR(20)
                              CHECK (atributo IN ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor                 INT NOT NULL,
    quantidade_escolhas   INT,
    ordem                 INTEGER NOT NULL DEFAULT 0,
    CHECK (
        (atributo IS NOT NULL AND quantidade_escolhas IS NULL)
        OR
        (atributo IS NULL AND quantidade_escolhas IS NOT NULL)
    )
);

CREATE INDEX idx_talento_atributos_talento_id ON talento_atributos(talento_id);

-- ===== Talentos raciais =====
-- Talentos quase biológicos, presos a uma raça específica — diferente do talento
-- normal (pré-requisito de atributo, opcional), aqui a raça e o nível mínimo são
-- sempre obrigatórios. Ficam num compêndio à parte no front (aba "Talentos Raciais").
CREATE TABLE talentos_raciais (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                                VARCHAR(64)   NOT NULL UNIQUE,
    nome                                VARCHAR(120)  NOT NULL,
    icone                               VARCHAR(20),
    historia                            TEXT,
    descricao                           TEXT,

    raca_id                             BIGINT NOT NULL REFERENCES racas(id) ON DELETE CASCADE,
    nivel_minimo                        INT NOT NULL
);

-- ===== Atributos recebidos ao pegar um talento racial (fixo ou à escolha) =====
-- Mesma estrutura de talento_atributos/raca_atributos.
CREATE TABLE talento_racial_atributos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talento_racial_id     BIGINT NOT NULL REFERENCES talentos_raciais(id) ON DELETE CASCADE,
    atributo              VARCHAR(20)
                              CHECK (atributo IN ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor                 INT NOT NULL,
    quantidade_escolhas   INT,
    ordem                 INTEGER NOT NULL DEFAULT 0,
    CHECK (
        (atributo IS NOT NULL AND quantidade_escolhas IS NULL)
        OR
        (atributo IS NULL AND quantidade_escolhas IS NOT NULL)
    )
);

CREATE INDEX idx_talento_racial_atributos_talento_racial_id ON talento_racial_atributos(talento_racial_id);
