CREATE TABLE talentos (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                                VARCHAR(64)   NOT NULL UNIQUE,
    nome                                VARCHAR(120)  NOT NULL,

    -- Símbolo exibido no compêndio (emoji), ex: '⚔️'.
    icone                               VARCHAR(20),

    historia                            TEXT,
    descricao                           TEXT,

    -- Atributo recebido ao pegar o talento — a maioria tem, alguns não.
    atributo_recebido                   VARCHAR(20)
                                             CHECK (atributo_recebido IN
                                                 ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor_atributo_recebido             INT,

    -- Pré-requisitos, ambos opcionais e combinados com E quando os dois existem.
    raca_requerida_id                   BIGINT REFERENCES racas(id),
    atributo_requerido                  VARCHAR(20)
                                             CHECK (atributo_requerido IN
                                                 ('forca','destreza','constituicao','inteligencia','sabedoria','carisma')),
    valor_minimo_atributo_requerido     INT,

    CHECK (
        (atributo_recebido IS NULL) = (valor_atributo_recebido IS NULL)
    ),
    CHECK (
        (atributo_requerido IS NULL) = (valor_minimo_atributo_requerido IS NULL)
    )
);
