-- Dados reais migrados de TALENTOS_DATA (js/compendium/data-talents.js)

INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adepto-marcial', 'Adepto Marcial', 'combate', '⚔️', NULL, 'Treinamento marcial avançado que permite realizar manobras de combate especiais do arquétipo Mestre de Batalha.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('alerta', 'Alerta', 'combate', '👁️', NULL, 'Sempre atento ao perigo, você reage mais rápido e nunca é pego de surpresa.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('ambidestro', 'Ambidestro', 'combate', '🗡️', NULL, 'Domínio do estilo com duas armas, oferecendo proteção e velocidade de ataque superiores.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('atacante-bestial', 'Atacante Bestial', 'combate', '🐾', NULL, 'Seus golpes corpo a corpo são devastadores — você pode repetir o dado de dano e escolher o melhor resultado.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('atirador-aguçado', 'Atirador Aguçado', 'combate', '🏹', NULL, 'Domínio total de armas à distância: ignore alcance, cobertura e troque precisão por poder de fogo.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('combatente-montado', 'Combatente Montado', 'combate', '🐴', NULL, 'Oponente perigoso quando montado, com vantagem sobre alvos menores e proteção para a montaria.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('duelista-defensivo', 'Duelista Defensivo', 'combate', '🤺', 'Destreza 13 ou maior', 'Ao ser atingido por ataque corpo a corpo, usa sua reação para adicionar o bônus de proficiência à CA.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('especialista-veneno', 'Especialista em Veneno', 'combate', '🧪', 'Proficiência com kit de Alquimia.', 'Mestre na criação e aplicação de venenos letais que ignoram resistências.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('esmagador', 'Esmagador', 'combate', '🔨', NULL, 'Especialista em dano contundente: empurra inimigos e explora críticos para dominar o campo de batalha.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('especialista-besta', 'Especialista em Besta', 'combate', '🔫', NULL, 'Domínio completo de bestas: ignore a recarga, atire próximo a inimigos e use ação bônus para atacar.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('especialista-briga', 'Especialista em Briga', 'combate', '👊', NULL, 'Veterano de brigas usando qualquer coisa como arma. Seus golpes desarmados causam mais dano.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('imobilizador', 'Imobilizador', 'combate', '🪢', 'Força 13 ou maior', 'Especialista em prender e imobilizar oponentes em combate engajado.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('iniciado-combate', 'Iniciado em Combate', 'combate', '🛡️', 'Proficiência com arma marcial', 'Treinamento marcial único que ensina um Estilo de Luta da lista do guerreiro.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('investida-poderosa', 'Investida Poderosa', 'combate', '💨', NULL, 'Ao usar Disparada, pode atacar ou empurrar com ação bônus — e ganhar bônus ao se mover antes.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('lacerador', 'Lacerador', 'combate', '🗡️', NULL, 'Cortes precisos reduzem o deslocamento do inimigo e impõem desvantagem em críticos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('maestria-arma-haste', 'Maestria em Arma de Haste', 'combate', '🪄', 'Proficiência com armas de Haste', 'Mantém inimigos afastados e ataca com a extremidade oposta como ação bônus.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('matador-conjuradores', 'Matador de Conjuradores', 'combate', '🔮', NULL, 'Técnicas especializadas para combater conjuradores em distâncias curtas.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adepto-armas', 'Adepto de Armas', 'combate', '⚙️', NULL, 'Treinamento extensivo com uma variedade de armas simples e marciais.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mestre-armas-grandes', 'Mestre de Armas Grandes', 'combate', '🪓', 'Força 13 ou maior e proficiência com pelo menos uma arma pesada', 'Usa o peso das armas pesadas a seu favor, com ataques bônus em críticos e dano devastador.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mestre-escudo', 'Mestre de Escudo', 'combate', '🛡️', 'Proficiência com escudos', 'Usa o escudo como arma ofensiva e proteção extra contra magias e efeitos de área.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mobilidade', 'Mobilidade', 'combate', '💨', NULL, 'Movimentação excepcional: mais velocidade, ignore terreno difícil ao disparar e evite contra-ataques.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('perfurador', 'Perfurador', 'combate', '🗡️', NULL, 'Precisão cirúrgica com dano perfurante: relance dados e potencialize críticos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('sentinela', 'Sentinela', 'combate', '🗡️', NULL, 'Dominador do ataque de oportunidade: para inimigos na fuga, pune quem desengaja e protege aliados.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('tita-ataque', 'Titã de Ataque', 'combate', '💪', 'Força 15 ou maior', 'Força imparável no campo de batalha: ignore a propriedade de duas mãos e destrua em sequência.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('maestria-armadura-media', 'Maestria em Armadura Média', 'defesa', '🛡️', 'Proficiência em armadura média', 'Usa armadura média sem penalidade de furtividade e extrai o máximo de proteção com alta Destreza.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('maestria-armadura-pesada', 'Maestria em Armadura Pesada', 'defesa', '🛡️', 'Proficiência em armadura pesada', 'Armadura pesada reduz dano físico não-mágico recebido em 3 e aumenta a CA.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('resiliente', 'Resiliente', 'defesa', '💠', NULL, 'Fortalece um atributo e concede proficiência no teste de resistência correspondente.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('resistente', 'Resistente', 'defesa', '🪨', NULL, 'Corpo resistente que recebe mais cura.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('robusto', 'Robusto', 'defesa', '❤️', NULL, 'Reserva de PV muito maior — cresce a cada nível ganho.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adepto-elemental', 'Adepto Elemental', 'magia', '🔥', 'Capacidade de conjurar pelo menos uma magia', 'Domina um tipo de dano elemental, ignorando resistências e relançando dados com resultado 1.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adepto-metamagico', 'Adepto Metamágico', 'magia', '✨', 'Habilidade de Conjuração ou Magia de Pacto', 'Aprende duas opções de Metamagia da lista do feiticeiro e ganha pontos de feitiçaria.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adepto-mistico', 'Adepto Místico', 'magia', '🌙', 'Habilidade de Conjuração ou Magia de Pacto', 'Desbloqueia uma Invocação Mística da classe do bruxo.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('atirador-magia', 'Atirador de Magia', 'magia', '⚡', 'Capacidade de conjurar pelo menos uma magia', 'Magias de ataque com o dobro do alcance, ignorando coberturas.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('conjurador-guerra', 'Conjurador de Guerra', 'magia', '⚔️', 'Capacidade de conjurar pelo menos uma magia', 'Conjura magias no meio do combate com maestria, mantendo concentração e usando ataques de oportunidade mágicos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('conjurador-ritual', 'Conjurador de Ritual', 'magia', '📜', 'Inteligência ou Sabedoria 13 ou maior', 'Aprende e conjura magias como rituais a partir de um livro especial.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('iniciado-artifice', 'Iniciado Artífice', 'magia', '⚙️', NULL, 'Aprende habilidades dos artífices: um truque, uma magia de 1º nível e proficiência com ferramenta.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('iniciado-magia', 'Iniciado em Magia', 'magia', '📖', NULL, 'Aprende dois truques e uma magia de 1º nível de outra classe conjuradora.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('telepático', 'Telepático', 'magia', '🧠', NULL, 'Comunica-se telepaticamente e lê pensamentos sem usar espaços de magia.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('tocado-sombras', 'Tocado pelas Sombras', 'magia', '🌑', NULL, 'Magia sombria modificou você: aprende Invisibilidade e uma magia de ilusão ou necromancia.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('atleta', 'Atleta', 'habilidade', '🏃', NULL, 'Treinamento físico intenso melhora movimentação, escalada e saltos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('explorador-cavernas', 'Explorador de Cavernas', 'habilidade', '🗺️', NULL, 'Detecta armadilhas e portas secretas com facilidade, e resiste melhor aos seus efeitos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('especializado-pericia', 'Especializado em Perícia', 'habilidade', '🎯', NULL, 'Aprimora uma perícia à escolha, concedendo especialidade e aumentando um atributo.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mente-afiada', 'Mente Afiada', 'habilidade', '🧭', NULL, 'Memória perfeita e senso de orientação infalível — nunca se perde nem esquece nada.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('observador', 'Observador', 'habilidade', '🔍', NULL, 'Percepção aguçada: lê lábios e possui altíssimos valores passivos de Percepção e Investigação.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('perito', 'Perito', 'habilidade', '📚', NULL, 'Proficiência em três perícias ou ferramentas à escolha.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('poliglota', 'Poliglota', 'habilidade', '🗣️', NULL, 'Domínio de idiomas e criptografia: aprende três línguas e cria códigos indecifráveis.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('sorrateiro', 'Sorrateiro', 'habilidade', '🌑', 'Destreza 13 ou maior', 'Especialista em furtividade: se esconde na penumbra e mantém posição após errar ataques.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('ator', 'Ator', 'geral', '🎭', NULL, 'Mestre da mímica e do disfarce: vantagem em Atuação e Enganação ao se passar por outra pessoa.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('chef', 'Chef', 'geral', '🍖', NULL, 'Cozinheiro habilidoso que prepara alimentos que curam e concedem PV temporários.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('curandeiro', 'Curandeiro', 'geral', '⚕️', NULL, 'Cirurgião capacitado que estabiliza aliados com PV e cura de forma eficiente.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('lider-inspirador', 'Líder Inspirador', 'geral', '👑', 'Carisma 13 ou maior', 'Inspira aliados com um discurso de 10 minutos, concedendo PV temporários.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('sortudo', 'Sortudo', 'geral', '🍀', NULL, 'Sorte inexplicável: rerrole dados em momentos críticos usando pontos de sorte.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('intimidacao-brutal', 'Intimidação Brutal', 'habilidade', '💪', NULL, 'Sua presença física é mais assustadora do que palavras.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('vontade-resistente', 'Vontade Resistente', 'defesa', '🫀', NULL, 'Sua vitalidade impede que você sucumba facilmente à morte.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('leitura-combate', 'Leitura de Combate', 'combate', '👁️', NULL, 'Você analisa padrões de ataque e defesa durante o combate.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('passo-calculado', 'Passo Calculado', 'defesa', '🧭', NULL, 'Você se move com precisão, evitando riscos desnecessários.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('sobrevivente-nato', 'Sobrevivente Nato', 'geral', '🌿', NULL, 'Você resiste melhor às adversidades naturais e situações extremas.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('reacao-instintiva', 'Reação Instintiva', 'habilidade', '⚡', NULL, 'Seu corpo reage antes mesmo de você pensar.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('foco-disciplinado', 'Foco Disciplinado', 'magia', '🎯', NULL, 'Você mantém concentração e precisão mesmo sob pressão.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('leitor-intencoes', 'Leitor de Intenções', 'habilidade', '🧠', NULL, 'Você lê microexpressões e intenções ocultas, detectando mentiras e hostilidade com precisão.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('olhar-analitico', 'Olhar Analítico', 'habilidade', '🔍', NULL, 'Você avalia rapidamente criaturas e identifica padrões físicos e fraquezas.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('improvisador', 'Improvisador', 'geral', '🛠️', NULL, 'Você transforma qualquer objeto em ferramenta útil, encontrando soluções mesmo sem o equipamento adequado.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('planejador-nato', 'Planejador Nato', 'geral', '🧭', 'Inteligência 13 ou maior', 'Você antecipa cenários e prepara aliados com instruções táticas antes da ação começar.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mente-inabalavel', 'Mente Inabalável', 'habilidade', '🧱', NULL, 'Sua mente resiste a manipulações externas e efeitos debilitantes.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('intervencao-rapida', 'Intervenção Rápida', 'geral', '⚡', NULL, 'Você reage rapidamente a situações inesperadas, auxiliando aliados no momento crítico.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('momentos-heroicos', 'Momentos Heroicos', 'geral', '🌟', NULL, 'Você ultrapassa seus limites quando mais precisa.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('adaptado-a-noite', 'Adaptado à Noite', 'geral', '🌙', NULL, 'Seu corpo se acostumou à ausência de luz e descanso irregular.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('sentido-sismico', 'Sentido Sísmico', 'habilidade', '🌍', 'Proficiência em Percepção', 'Você percebe o ambiente através das vibrações do solo.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('especialista-anatomia', 'Especialista em Anatomia', 'habilidade', '🫀', 'Inteligência ou Sabedoria 13 ou maior', 'Você estudou criaturas e sabe exatamente onde atingir.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('ataque-preciso', 'Ataque Preciso', 'combate', '🎯', NULL, 'Você maximiza precisão em condições favoráveis.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('valentao', 'Valentão', 'combate', '👊', NULL, 'Você gosta de bater em pessoas mais fracas que você.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('afortunado', 'Afortunado', 'geral', '🎲', NULL, 'A sorte parece sorrir para você em momentos aleatórios.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('vicio-apostas', 'Vício em Apostas', 'geral', '🃏', NULL, 'Você vive no risco constante, com resultados imprevisíveis.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('multi-tarefa', 'Multitarefa', 'geral', '🧩', NULL, 'Você executa múltiplas atividades simultaneamente.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mestre-alquimia', 'Mestre de Alquimia', 'geral', '⚗️', NULL, 'Você domina a criação e manipulação de compostos alquímicos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('mestre-ferreiro', 'Mestre Ferreiro', 'geral', '🔨', NULL, 'Você domina a criação e modificação de armas e armaduras.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('capitalista', 'Capitalista', 'geral', '💰', NULL, 'Você domina a arte do comércio e lucro.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('evasivo', 'Evasivo', 'defesa', '💨', NULL, 'Você evita ataques com extrema eficiência.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('explorador-masmorras', 'Explorador de Masmorras', 'geral', '🏰', NULL, 'Você domina ambientes confinados e perigosos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('ossos-de-colosso', 'Ossos de Colosso', 'defesa', '🦴', 'Constituição 15 ou maior', 'Seu corpo resiste como aço, absorvendo impactos pesados.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('resistencia-sob-pressao', 'Resistência Sob Pressão', 'defesa', '🔥', NULL, 'Quanto mais ferido você está, mais difícil é derrubá-lo.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('equilibrio-perfeito', 'Equilíbrio Perfeito', 'defesa', '⚖️', 'Destreza 13 ou maior', 'Você mantém postura impecável mesmo em situações adversas.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('reserva-arcana', 'Reserva Arcana', 'magia', '🔋', 'Capacidade de conjurar magia e personagem de 5° nível ou superior.', 'Você possui energia mágica adicional para momentos críticos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('explosao-controlada', 'Explosão Controlada', 'magia', '💣', NULL, 'Você molda suas magias para evitar aliados.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('conjuracao-economica', 'Conjuração Econômica', 'magia', '📉', 'Capacidade de conjurar magia', 'Você otimiza o uso de energia mágica, reduzindo desperdícios.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('ancora-arcana', 'Âncora Arcana', 'magia', '⚓', 'Capacidade de conjurar magia com concentração', 'Você fixa suas magias no tecido da realidade, tornando-as mais difíceis de dissipar.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('alcance-flexivel', 'Alcance Flexível', 'magia', '📏', 'Capacidade de conjurar magia', 'Você manipula o alcance de suas magias com precisão.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('retencao-magica', 'Retenção Mágica', 'magia', '🧠', 'Capacidade de conjurar magia', 'Você segura o fluxo da magia antes de liberá-la.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('contrafluxo', 'Contrafluxo', 'magia', '🔄', 'Capacidade de conjurar magia', 'Você manipula energia mágica residual ao seu redor.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('estabilidade-ritual', 'Estabilidade Ritual', 'magia', '📜', 'Capacidade de conjurar rituais', 'Seus rituais são mais seguros e rápidos.');
INSERT INTO talentos (id, nome, categoria, icone, prereq, descricao) VALUES ('eco-defensivo', 'Eco Defensivo', 'magia', '🛡️', 'Capacidade de conjurar magia', 'Resquícios mágicos protegem você após conjuração.');

INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-marcial', 'Aprende duas manobras à sua escolha da lista do Mestre de Batalha.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-marcial', 'CD das manobras: 8 + bônus de proficiência + mod. de Força ou Destreza.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-marcial', 'Ganha 1 dado de superioridade d6 (ou mais 1 se já possuir); recuperado em descanso curto ou longo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('alerta', '+5 de bônus em iniciativa.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('alerta', 'Não pode ser surpreendido enquanto estiver consciente.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('alerta', 'Outras criaturas não ganham vantagem em ataques por não serem visíveis para você.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ambidestro', '+1 de bônus na CA enquanto empunhar uma arma corpo a corpo em cada mão.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ambidestro', 'Pode usar combater com duas armas mesmo que a arma não seja leve.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ambidestro', 'Pode sacar ou guardar duas armas de uma mão de uma só vez.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atacante-bestial', 'Ao rolar dano em ataque corpo a corpo com arma, pode relançar o dado de dano da arma e usar qualquer dos valores.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-aguçado', 'Atacar além do alcance normal não impõe desvantagem.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-aguçado', 'Ataques à distância ignoram meia-cobertura e três-quartos de cobertura.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-aguçado', 'Pode sofrer –5 na jogada de ataque para ganhar +10 no dano.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('combatente-montado', 'Vantagem em ataques corpo a corpo contra criaturas desmontadas menores que sua montaria.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('combatente-montado', 'Pode forçar ataques direcionados à montaria para si mesmo.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('combatente-montado', 'Sua montaria não sofre dano em testes de resistência de Destreza bem-sucedidos.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('duelista-defensivo', 'Reação: adiciona o bônus de proficiência à CA quando atingido por ataque corpo a corpo.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('duelista-defensivo', 'Requer empunhar uma arma de acuidade com proficiência.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-veneno', 'Você recebe resistência a dano venenoso.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-veneno', 'Você recebe um bonus de +3 em rolagem de fabricação de poções do tipo veneno.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-veneno', 'Dano de veneno criado por você é aumentado em uma quantidade igual ao seu bônus de proficiência.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-veneno', 'Você pode usar uma ação bônus para aplicar veneno em uma arma ou projétil.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('esmagador', '+1 em Força ou Constituição (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('esmagador', 'Uma vez por turno, ao acertar dano contundente, pode mover o alvo até 1,5 m.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('esmagador', 'Ao acertar um crítico com dano contundente, ataques subsequentes contra o alvo têm vantagem até seu próximo turno.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-besta', 'Ignora a propriedade de recarga de bestas com ação bônus.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-besta', 'Estar a 1,5 m de inimigos não impõe desvantagem nos ataques.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-besta', 'Ao usar ação de Ataque com arma de uma mão, pode usar ação bônus para atacar com besta de mão.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-briga', '+1 em Força ou Constituição (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-briga', 'Ataques desarmados ou com armas improvisadas causam 1d4 de dano extra.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-briga', 'Ao acertar ataque desarmado ou improvisado, pode usar ação bônus para tentar agarrar o alvo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('imobilizador', 'Vantagem em jogadas de ataque contra criaturas agarradas.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('imobilizador', 'Ação: pode imobilizar criatura agarrada com outro teste de agarrar (ambos ficam impedidos).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-combate', '+1 em Força ou Destreza (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-combate', 'Aprende um Estilo de Luta à sua escolha da lista de estilos de luta do guerreiro.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-combate', 'Pode trocar o estilo ao subir de nível.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('investida-poderosa', 'Ao usar Disparada, ação bônus para atacar corpo a corpo ou empurrar.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('investida-poderosa', 'Se mover pelo menos 3 m antes do ataque: +5 no dano ou empurra até 3 m.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('lacerador', '+1 em Força ou Destreza (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('lacerador', 'Uma vez por turno, ao acertar dano cortante, reduz deslocamento do alvo em 3 m até seu próximo turno.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('lacerador', 'Crítico com dano cortante: alvo sofre desvantagem em ataques até o próximo turno.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-arma-haste', 'Ao atacar com glaive, alabarda ou bordão, você pode usar uma ação bônus para atacar com a outra extremidade (1d4 contundente).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-arma-haste', 'Criaturas que entrarem no seu alcance enquanto empunha armas de haste provocam ataques de oportunidade.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('matador-conjuradores', 'Reação: ao ver criatura a até 1,5 m conjurar, pode realizar ataque corpo a corpo contra ela.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('matador-conjuradores', 'Dano em criatura concentrada causa desvantagem no teste de concentração.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('matador-conjuradores', 'Vantagem em testes de resistência contra magias de criaturas a até 1,5 m.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-armas', '+1 em Força ou Destreza (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-armas', 'Ganha proficiência com todas as armas.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-armas-grandes', 'Você causa o dobro de dano a construções e objetos.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-armas-grandes', 'Ao acertar um acerto crítico ou reduzir alvo a 0 PV, você pode como parte desse mesmo ataque atingir uma outra criatua que esteja em seu alcance desde que a rolagem original também à atinja.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-armas-grandes', 'Antes de realizar um ataque com arma pesada você pode escolher sofrer –5 na jogada de ataque para ganhar +10 no dano.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-escudo', 'Com uma ação bônus você pode empurrar uma criatura no alcance, para trás a até 3m de distância.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-escudo', 'Adiciona o bônus de CA do escudo a testes de resistência de Destreza.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-escudo', 'Quando um aliado a até 1,5m de você for alvo de um ataque corpo a corpo, você pode usar sua reação para impor desvantagem no ataque. Essa habilidade funciona em conjunto com o estilo de luta Defensor.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mobilidade', 'Deslocamento aumenta em 3 metros.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mobilidade', 'Ao usar Disparada, terreno difícil não custa movimento adicional.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mobilidade', 'Ao atacar uma criatura corpo a corpo, ela não provoca ataque de oportunidade de você pelo resto do turno.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('perfurador', '+1 em Força ou Destreza (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('perfurador', 'Uma vez por turno, ao acertar dano perfurante, pode relançar um dado de dano e escolher o resultado.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('perfurador', 'Crítico com dano perfurante: rola um dado de dano adicional.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sentinela', 'Ao acertar ataque de oportunidade, o deslocamento da criatura se torna 0 e você pode mover o alvo 1,5 m em qualquer direção. Se o alvo colidir com obstáculo ou criatura, sofre dano extra igual ao bônus de proficiência.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sentinela', 'Criaturas provocam ataque de oportunidade mesmo ao usar Desengajar.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('tita-ataque', 'Você pode ignorar a propriedade de duas mãos de armas pesadas.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('tita-ataque', 'Ao se mover pelo menos 3 m antes de atacar, rola dano duas vezes e fica com o melhor.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-media', 'Armadura média não impõe desvantagem em Furtividade.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-media', 'Recebe um bonus de +1 em CA se tiver Destreza 16 ou maior e estiver usando armadura média.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-media', 'Se tiver Destreza 16 ou maior e estiver usando armadura média, recebe um bonus de +1 em testes de resistência de Destreza.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-pesada', 'Dano de concussão, cortante e perfurante não-mágico recebido é reduzido em 3.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-pesada', 'Se tiver Força 16 ou maior e estiver usando armadura pesada, recebe um bonus de +1 em CA.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('maestria-armadura-pesada', 'Se tiver Força 16 ou maior e estiver usando armadura pesada, recebe um bonus de +1 em testes de resistência de Força.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resiliente', '+1 no valor de habilidade escolhido (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resiliente', 'Ganha proficiência em testes de resistência com a habilidade escolhida.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resistente', '+1 em Constituição (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resistente', 'Ao receber uma cura, ela é aumentada em 50%.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('robusto', '+1 em Constituição (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('robusto', 'Máximo de PV aumenta em 3 × nível atual ao adquirir o talento.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('robusto', 'Cada nível subsequente concede +3 PV adicionais.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-elemental', 'Escolha um tipo: ácido, elétrico, fogo, frio ou trovão.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-elemental', 'Suas magias ignoram resistência ao tipo escolhido.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-elemental', 'Ao rolar dano com esse tipo, pode relançar qualquer dado com resultado 1.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-metamagico', 'Aprende duas opções de Metamagia da lista do feiticeiro.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-metamagico', 'Ganha 2 pontos de feitiçaria para usar com Metamagia.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-metamagico', 'Pode substituir uma opção de Metamagia ao subir de nível.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-metamagico', 'Recupera todos os pontos em descanso longo.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-mistico', 'Aprende uma Invocação Mística da lista do bruxo.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-mistico', 'Se a invocação tiver requisito, só pode escolhê-la se for bruxo e cumpri-lo.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adepto-mistico', 'Pode trocar a invocação por outra ao subir de nível.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-magia', 'Magias que exigem jogada de ataque têm o alcance dobrado.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-magia', 'Ataques à distância com magia ignoram meia-cobertura e três-quartos de cobertura.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atirador-magia', 'Aprende um truque de ataque de uma lista à escolha.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-guerra', 'Vantagem em testes de Constituição para manter concentração após sofrer dano.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-guerra', 'Pode realizar componentes somáticos mesmo com armas ou escudo nas mãos.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-guerra', 'Quando uma criatura provocar ataque de oportunidade contra você, você pode com uma reação conjurar uma magia com tempo de conjuração de ação ou ação bônus com um alvo no lugar.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-ritual', 'Recebe um livro de rituais com duas magias de 1º nível com o descritor ritual.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-ritual', 'Escolha bardo, bruxo, clérigo, druida, feiticeiro ou mago para definir o atributo de conjuração.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjurador-ritual', 'Pode adicionar magias rituais encontradas ao livro (2h + 50 po por nível).', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-artifice', 'Aprende um truque e uma magia de 1º círculo do artífice (Inteligência).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-artifice', 'Pode conjurar a magia de 1º círculo gratuitamente uma vez por descanso longo.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-artifice', 'Proficiência com um tipo de ferramenta de artesão (pode ser foco de conjuração).', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-magia', 'Escolha uma classe: bardo, bruxo, clérigo, druida, feiticeiro ou mago.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-magia', 'Aprende dois truques da lista da classe escolhida.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('iniciado-magia', 'Aprende uma magia de 1º nível da mesma classe; pode conjurá-la uma vez por descanso longo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('telepático', '+1 em Inteligência, Sabedoria ou Carisma (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('telepático', 'Fala telepaticamente com criaturas à vista até 18 m (deve conhecer o idioma).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('telepático', 'Pode conjurar Detectar Pensamentos sem espaço de magia ou componentes.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('tocado-sombras', '+1 em Inteligência, Sabedoria ou Carisma (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('tocado-sombras', 'Aprende Invisibilidade e uma magia de 1º círculo (Ilusão ou Necromancia).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('tocado-sombras', 'Pode conjurar ambas sem espaço de magia; recupera após descanso longo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atleta', '+1 em Força ou Destreza (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atleta', 'Se levantar do chão custa apenas 1,5 m de deslocamento.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atleta', 'Escalar não custa deslocamento adicional.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('atleta', 'Salto em distância/altura com apenas 1,5 m de corrida.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-cavernas', 'Vantagem em Percepção e Investigação para detectar portas secretas.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-cavernas', 'Vantagem em testes de resistência contra armadilhas.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-cavernas', 'Resistência a dano causado por armadilhas.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-cavernas', 'Pode procurar armadilhas em ritmo normal de viagem.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especializado-pericia', '+1 em um atributo à escolha (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especializado-pericia', 'Proficiência em uma perícia à escolha.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especializado-pericia', 'Especialidade em uma perícia com proficiência (dobra o bônus de proficiência).', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-afiada', '+1 em Inteligência (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-afiada', 'Sempre sabe a direção do norte.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-afiada', 'Sempre sabe o tempo restante para o próximo nascer ou pôr do sol.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-afiada', 'Recorda com precisão qualquer coisa vista ou ouvida no último mês.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('observador', '+1 em Inteligência ou Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('observador', 'Pode ler lábios de criatura que fale idioma que compreenda.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('observador', '+5 nos valores passivos de Percepção e Investigação.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('perito', 'Ganha proficiência em qualquer combinação de três perícias ou ferramentas.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('poliglota', '+1 em Inteligência (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('poliglota', 'Aprende três idiomas à escolha.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('poliglota', 'Pode criar criptogramas: outros só decifram com sucesso em Inteligência (CD = Int + prof.) ou magia.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sorrateiro', 'Pode tentar se esconder quando estiver levemente obscurecido.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sorrateiro', 'Errar um ataque à distância estando escondido não revela sua posição.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sorrateiro', 'Penumbra não impõe desvantagem em testes de Percepção visual.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ator', '+1 em Carisma (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ator', 'Vantagem em Atuação e Enganação ao se disfarçar.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ator', 'Pode imitar a voz ou sons de qualquer criatura ouvida por ao menos 1 minuto.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('chef', '+1 em Constituição ou Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('chef', 'Proficiência com Utensílios de Cozinheiro.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('chef', 'Descanso curto: prepara refeição para prof.+4 criaturas que recuperam 1d8 PV extras ao gastar Dados de Vida.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('chef', 'Descanso longo: cria aperitivos (= bônus de prof.) que concedem PV temporários iguais ao bônus de proficiência.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('curandeiro', 'Ao estabilizar criatura morrendo com kit de primeiros-socorros, ela recupera 1 PV.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('curandeiro', 'Ação: gasta kit para restaurar 1d6+4 + Dados de Vida totais da criatura em PV (uma vez por descanso).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('lider-inspirador', '10 minutos: até 6 criaturas amigáveis recebem PV temporários = nível + mod. de Carisma.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('lider-inspirador', 'Criaturas só podem se beneficiar novamente após descanso curto ou longo.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sortudo', '3 pontos de sorte recuperados em descanso longo.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sortudo', 'Gasta 1 ponto para rolar d20 adicional em qualquer ataque, teste ou resistência — escolhendo qual usar.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sortudo', 'Também pode influenciar ataques de inimigos contra você.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sortudo', 'Pontos se cancelam se múltiplas criaturas os usam na mesma jogada.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intimidacao-brutal', 'Você pode usar Força em vez de Carisma em testes de Intimidação.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intimidacao-brutal', 'Se estiver adjacente ao alvo, adiciona +2 ao teste.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intimidacao-brutal', 'Em caso de sucesso por 5 ou mais, o alvo não pode se aproximar voluntariamente de você até o fim do próximo turno.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vontade-resistente', 'Você adiciona seu modificador de Constituição em testes de resistência contra morte.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vontade-resistente', 'Ao obter 3 sucessos em teste de morte, recupera 1 PV.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vontade-resistente', 'Em um sucesso crítico você ignora penalidade de ferimento.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('leitura-combate', 'Uma vez por turno, ao errar um ataque, recebe +2 na próxima jogada de ataque contra o mesmo alvo até o fim do turno.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('leitura-combate', 'Se acertar esse ataque, o alvo recebe uma penalidade de -2 na próxima jogada de ataque contra você.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('passo-calculado', 'Ao se mover metade do seu deslocamento ou menos no turno, recebe +2 na CA até o início do próximo turno.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('passo-calculado', 'Esse bônus não se aplica se estiver com armadura pesada.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sobrevivente-nato', 'Recebe +2 em testes de resistência contra exaustão.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sobrevivente-nato', 'Pode passar o dobro do tempo normal sem comida ou água antes de sofrer penalidades.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sobrevivente-nato', 'Testes para rastrear você têm CD aumentada em +2.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('reacao-instintiva', 'Adiciona o seu bônus de proficiência em testes de Iniciativa.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('reacao-instintiva', 'Na primeira rodada de combate, se ainda não tiver agido, recebe um bônus na CA igual ao seu bônus de proficiência.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('foco-disciplinado', 'Recebe +2 em testes de Constituição para manter concentração.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('foco-disciplinado', 'Ao falhar por 2 ou menos, pode repetir o teste mais uma única vez.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('leitor-intencoes', '+1 em Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('leitor-intencoes', '+5 em testes de Intuição para detectar mentiras.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('olhar-analitico', 'Ação bônus: escolha uma criatura a até 12 m e realize um teste de Intuição (CD = 10 + metade do CR da criatura ou 10 + mod. de Enganação do alvo).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('olhar-analitico', 'Em sucesso, você descobre uma resistência, imunidade ou vulnerabilidade da criatura (à escolha do mestre).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('olhar-analitico', 'Em um sucesso por 5 ou mais, pode escolher qual dessas informações deseja saber.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('improvisador', 'Você pode usar um kit de ferramentas diferente do necessário; a rolagem é feita com desvantagem.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('improvisador', 'Você recebe proficiência em um kit de ferramenta à sua escolha.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('improvisador', 'Você consome metade do material em produção.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('planejador-nato', 'Após 1 minuto de planejamento, escolha até 6 criaturas aliadas.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('planejador-nato', 'Cada uma pode adicionar 1d6 a uma única jogada de ataque, teste de habilidade ou resistência nas próximas 1 hora.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('planejador-nato', 'Uma criatura só pode se beneficiar uma vez por uso deste talento.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('planejador-nato', 'Pode usar essa habilidade uma vez por descanso curto ou longo.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-inabalavel', '+2 em testes de resistência contra ser Amedrontado ou Enfeitiçado.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-inabalavel', 'Reação: ao falhar em um teste contra esses efeitos, pode repetir o teste.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-inabalavel', 'Em sucesso, torna-se imune ao mesmo efeito pela duração original.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mente-inabalavel', 'Pode usar essa reação uma vez por descanso curto.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intervencao-rapida', 'Reação: quando um aliado a até 1,5 m falhar em um teste de habilidade ou resistência, você pode conceder +1d6 ao resultado.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intervencao-rapida', 'Se isso transformar a falha em sucesso, o aliado pode se mover até 3 m sem provocar ataques de oportunidade.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('intervencao-rapida', 'Pode usar essa reação um número de vezes igual ao bônus de proficiência por descanso longo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('momentos-heroicos', '+1 em Constituição (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('momentos-heroicos', 'No momento que você for levado a 0 pontos de vida, você pode usar sua reação para realizar uma ação completa.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('momentos-heroicos', 'Você pode usar essa habilidade uma vez por descanso longo.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adaptado-a-noite', '+1 em Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adaptado-a-noite', 'Você adquire visão no escuro de 9 m, ou aumenta em 9 m se já possuir.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adaptado-a-noite', 'Você não sofre desvantagem em qualquer teste de perícia realizado na escuridão total.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('adaptado-a-noite', 'Recebe +2 em testes contra exaustão causada por falta de descanso.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sentido-sismico', '+1 em Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('sentido-sismico', 'Enquanto estiver cego ou de olhos fechados, você possui visão sísmica em 9 m.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-anatomia', 'Escolha dois tipos de criatura.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-anatomia', 'Seus ataques contra esses tipos são críticos com 19–20.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-anatomia', 'Ao realizar um acerto crítico, adiciona seu modificador de Inteligência ou Sabedoria ao dano.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('especialista-anatomia', 'Recebe +2 em testes para recordar informações sobre esses tipos.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ataque-preciso', 'Quando tiver vantagem em ataques, rola 3 dados em vez de 2.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ataque-preciso', 'Se tiver vantagem, seu crítico ocorre com 19–20.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('valentao', 'Sempre que você causar dano a uma criatura com ND menor que metade do seu nível, causa 1d10 de dano extra.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('valentao', 'Se o ND for menor que um quarto do seu nível, causa 2d10 de dano extra.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('afortunado', 'Rolagens de d100 envolvendo encontros ou tesouros que afetem você são feitas duas vezes, escolhendo o melhor resultado.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vicio-apostas', 'No início de cada turno, role 1d20.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vicio-apostas', 'Resultado par: +2 em ataques, testes e resistências até o próximo turno.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vicio-apostas', 'Resultado ímpar: –1 nessas rolagens.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vicio-apostas', '20: bônus se torna +3.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('vicio-apostas', '1: penalidade se torna –2.', 4);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('multi-tarefa', 'Você pode realizar duas ações no turno, desde que nenhuma seja Ataque ou conjuração de magia.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('multi-tarefa', 'Pode usar essa habilidade uma vez por descanso curto.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-alquimia', 'Ganha proficiência com kit de alquimia.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-alquimia', 'Duração de poções criadas por você é multiplicada pelo bônus de proficiência.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-alquimia', 'Pode gastar um uso extra do kit para rolar testes de fabricação com vantagem.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-ferreiro', 'Ganha proficiência com ferramentas de ferreiro.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-ferreiro', 'Itens criados por você possuem +1 em testes relacionados à sua função.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('mestre-ferreiro', 'Você reduz o custo de criação de itens metálicos em 25%.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('capitalista', '+1 em Carisma (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('capitalista', 'Ao rolagar um teste de Persuasão ou Enganação para obter lucro financeiro, role 1d6 e adicione ao teste.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('capitalista', 'Ao administrar um negócio, aumente os ganhos em 25% ou reduza os custos em 25%', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('evasivo', 'Ao usar Esquiva, recebe bônus de CA igual ao bônus de proficiência.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('evasivo', 'Recebe +2 em testes de resistência de Destreza enquanto estiver esquivando.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('evasivo', 'Reação: reduz pela metade dano que permitir teste de Destreza para metade.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-masmorras', '+1 em Sabedoria (máx. 20).', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-masmorras', 'Você e até 6 aliados não se perdem em masmorras.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-masmorras', 'Aliados a até 3 m recebem +2 em Percepção, Investigação e Sobrevivência para detectar armadilhas e caminhos.', 2);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explorador-masmorras', 'Luz fraca é tratada como luz plena para você.', 3);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ossos-de-colosso', 'Reduz todo dano físico (Concutente, Perfurante e Cortante) recebido em valor igual ao bonus de proficiencia.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resistencia-sob-pressao', 'Enquanto estiver com menos da metade dos PV, recebe +2 na CA.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('resistencia-sob-pressao', 'Recebe +2 em testes de resistência.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('equilibrio-perfeito', 'Não pode ser derrubado enquanto estiver consciente, a menos que fique incapacitado.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('equilibrio-perfeito', 'Recebe +2 na CA contra ataques feitos com vantagem.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('reserva-arcana', 'Ganha um espaço de magia adicional do menor nível disponível.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('reserva-arcana', 'Uma vez por descanso longo, pode recuperar um espaço de magia gasto como ação bônus.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explosao-controlada', 'Magias de área podem excluir um número de criaturas igual ao seu bonus de proficiência.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('explosao-controlada', 'Criaturas excluídas não sofrem dano nem efeitos.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjuracao-economica', 'Quando uma magia requer componentes verbais e somáticos, você pode ignorar um dos dois à sua escolha.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('conjuracao-economica', 'Uma vez por descanso longo, ao conjurar uma magia, pode tratar o seu custo em espaços de magia como se fosse de um nível inferior (mínimo 1º nível).', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ancora-arcana', 'Criaturas têm desvantagem em testes para dissipar ou encerrar suas magias.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('ancora-arcana', 'Se sua concentração for quebrada, o efeito da magia persiste até o final do turno atual.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('alcance-flexivel', 'Uma vez por turno, pode aumentar ou reduzir pela metade o alcance de uma magia.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('alcance-flexivel', 'Magias de toque podem ser conjuradas a até 3 m.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('retencao-magica', 'Ao preparar uma ação para conjurar magia, não precisa manter concentração até o gatilho ocorrer.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('retencao-magica', 'Se o gatilho não ocorrer, você não perde o espaço de magia.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('contrafluxo', 'Reação: quando uma criatura a até 9 m conjurar uma magia que você tenha preparada, você recebe +2 no próximo teste de resistência contra magia até o fim do turno.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('contrafluxo', 'Se passar no teste, pode mover-se 3 m sem provocar ataques de oportunidade.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('estabilidade-ritual', 'Tempo adicional para conjurar rituais é reduzido pela metade.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('estabilidade-ritual', 'Você não pode ser interrompido durante um ritual, a menos que fique incapacitado.', 1);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('eco-defensivo', 'Após conjurar uma magia de 1º nível ou superior, recebe +1 na CA até o início do próximo turno.', 0);
INSERT INTO talento_beneficios (talento_id, texto, ordem) VALUES ('eco-defensivo', 'Se a magia exigir concentração, o bônus aumenta para +2 até o início do seu próximo turno.', 1);